stages:
  split:
    cmd: ' '
    deps:
    - data/raw
    - src/data/data_split.py
  normalize:
    cmd: python src/data/normalize.py
    deps:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - data/processed/y_test.csv
    - data/processed/y_train.csv
    - src/data/normalize.py
    outs:
    - data/processed/X_test_scaled.csv
    - data/processed/X_train_scaled.csv
  gridsearch:
    cmd: python src/models/grid_search.py
    deps:
    - data/processed/X_train_scaled.csv
    - data/processed/y_train.csv
    - src/models/grid_search.py
    outs:
    - models/best_params.pkl
  training:
    cmd: python src/models/training.py
    deps:
    - data/processed/X_train_scaled.csv
    - data/processed/y_train.csv
    - src/models/training.py
    outs:
    - models/rf_lr_model.pkl
  evaluate:
    cmd: python src/models/evaluate.py
    deps:
    - data/processed/X_test_scaled.csv
    - data/processed/y_test.csv
    - models/rf_lr_model.pkl
    - src/models/evaluate.py
    outs:
    - data/prediction.csv
    metrics:
    - metrics/scores.json:
        cache: false
